name: Automated Testing

on:
  push:
    branches:
      - master

jobs:
  automatic_test:
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict -n

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Composer Require Checker
        run: composer crc

      - name: Composer Unused
        run: composer unuse

      - name: CS Check
        run: composer cs-check
#
      - name: PHPStan
        run: composer phpstan

      - name: PHPUnit
        run: composer phpunit
